version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python 3.8.10

    steps:
      - checkout 
      - run: pip install users/requirement.txt
    
    test: 
      - checkout
      - run: python3 customer.test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test