version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python 3.8.10
      steps:
        -checkout
      - run:
        command: | 
          pip install -r users/requirement.txt
      
      - run:
        name: Running tests
          command: |
            python3 test.py

      -store-artifacts:
        path: test-reports/
        destination: customer_app